# Generated by Django 4.2.3 on 2023-07-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marte_api', '0004_alter_tarefa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='user',
        ),
    ]
